name: Update README with Activity

on:
  schedule:
    - cron: '0 0 * * *' # 每天自動執行一次
  workflow_dispatch:     # 允許手動觸發

permissions:
  contents: write   # <-- 關鍵在這裡！一定要加上這行，允許寫入內容

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write # <-- 有時候這邊也需要加上
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: README.md
          token: ${{ secrets.REPO_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 3
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
